		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.darkerdepths]
			petrified = true

		[types.wood_type.enderscape]
			veiled = true
			celestial = true
			murublight = true

		[types.wood_type.gardens_of_the_dead]
			whistlecane = true
			soulblight = true

		[types.wood_type.natures_spirit]
			redwood = true
			sugi = true
			wisteria = true
			fir = true
			willow = true
			aspen = true
			maple = true
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

		[types.wood_type.spawn]
			rotten = true
			date = true

		[types.cake.natures_spirit]
			cheese_block = true

		[types.lantern.architects_palette]
			nether_brass_lantern = true

		[types.lantern.darkerdepths]
			glowshroom_lantern = true

		[types.lantern.enderscape]
			bulb_lantern = true

		[types.lantern.natures_spirit]
			paper_lantern = true
			white_paper_lantern = true
			light_gray_paper_lantern = true
			gray_paper_lantern = true
			black_paper_lantern = true
			brown_paper_lantern = true
			red_paper_lantern = true
			orange_paper_lantern = true
			yellow_paper_lantern = true
			lime_paper_lantern = true
			green_paper_lantern = true
			blue_paper_lantern = true
			light_blue_paper_lantern = true
			cyan_paper_lantern = true
			purple_paper_lantern = true
			magenta_paper_lantern = true
			pink_paper_lantern = true

		[types.lantern.suppsquared]
			copper_lantern = true
			brass_lantern = true
			crimson_lantern = true

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.galosphere]
			opal = true

		[types.leaves_type.natures_spirit]
			frosty_redwood = true
			redwood = true
			sugi = true
			wisteria = true
			white_wisteria = true
			part_white_wisteria = true
			blue_wisteria = true
			part_blue_wisteria = true
			pink_wisteria = true
			part_pink_wisteria = true
			purple_wisteria = true
			part_purple_wisteria = true
			frosty_fir = true
			fir = true
			willow = true
			aspen = true
			yellow_aspen = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

		[types.leaves_type.spawn]
			date = true

		[entries.wood_type.architects_palette]
			railing = true
			board_wall = true
			boards = true
			board_stairs = true
			board_slab = true

		[entries.wood_type.farmersdelight]
			cabinet = true
